typography_spectrum: 0.12823102530092
color:
  brandStrength: 0.04444557265378535
  lightness: 0.17298759310506284
  saturation: 0.7268286899197847
  rhythmicContrast: 0.6464318232610822
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
layout_spectrum: 0.8904234215151519
author:
  email: hello@porcelain.love
name: PORCELAIN.LOVE
navigation:
  - id: 'http://www.porcelain.love/about'
    url: 'http://www.porcelain.love/about'
    name: About
    type: external
  - id: 'http://www.pocelain.love/gallery/prague2016'
    url: 'http://www.pocelain.love/gallery/prague2016'
    name: Prague 2016
    type: external
  - id: 'http://www.porcelain.love/gallery'
    url: 'http://www.porcelain.love/gallery'
    name: Gallery
    type: external
  - id: 'http://www.porcelain.love/management'
    url: 'http://www.porcelain.love/management'
    name: Management
    type: external
  - id: 'http://www.porcelain.love/events'
    url: 'http://www.porcelain.love/events'
    name: Events
    type: external
